# MCP Airlock Hackathon Demo Configuration
# Showcases all security features with easy local setup

server:
  addr: ":8080"
  public_base_url: "http://localhost:8080"
  timeouts:
    read: "30s"
    write: "30s"
    idle: "120s"

# JWT Authentication (demo mode)
auth:
  jwt_secret: "demo-secret-key-for-hackathon-only"  # DO NOT use in production
  audience: "mcp-airlock"
  issuer: "airlock-demo"
  clock_skew: "5m"
  required_groups: []  # Allow all groups for demo

# OPA Policy Engine with hot-reload
policy:
  rego_file: "configs/policy.rego"
  cache_ttl: "10s"  # Fast reload for demo
  reload_signal: "SIGHUP"

# Virtual root mappings with security
roots:
  - name: "public-docs"
    type: "fs"
    virtual: "mcp://docs/"
    real: "./examples/sample-docs/public"
    read_only: true
  - name: "sensitive-docs"
    type: "fs" 
    virtual: "mcp://sensitive/"
    real: "./examples/sample-docs/sensitive"
    read_only: true
  - name: "temp-storage"
    type: "fs"
    virtual: "mcp://temp/"
    real: "/tmp/airlock-demo"
    read_only: false

# Data Loss Prevention - showcases PII redaction
dlp:
  patterns:
    - name: "email"
      regex: '(?i)[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}'
      replace: "[REDACTED-EMAIL]"
    - name: "phone"
      regex: '(?i)(\+?1[-.\s]?)?\(?[0-9]{3}\)?[-.\s]?[0-9]{3}[-.\s]?[0-9]{4}'
      replace: "[REDACTED-PHONE]"
    - name: "ssn"
      regex: '(?i)\b\d{3}-?\d{2}-?\d{4}\b'
      replace: "[REDACTED-SSN]"
    - name: "credit_card"
      regex: '(?i)\b(?:\d{4}[-\s]?){3}\d{4}\b'
      replace: "[REDACTED-CC]"
    - name: "bearer_token"
      regex: '(?i)bearer\s+[a-z0-9._-]+'
      replace: "[REDACTED-TOKEN]"
    - name: "api_key"
      regex: '(?i)(api[_-]?key|token|secret)["\s]*[:=]["\s]*[a-z0-9._-]+'
      replace: "[REDACTED-API-KEY]"
    - name: "aws_key"
      regex: '(?i)(AKIA[0-9A-Z]{16})'
      replace: "[REDACTED-AWS-KEY]"
    - name: "password"
      regex: '(?i)(password|pass)["\s]*[:=]["\s]*[^\s\n]+'
      replace: "[REDACTED-PASSWORD]"

# Role-based rate limiting
rate_limiting:
  per_token: "100/min"  # Default for demo
  per_ip: "500/min"
  burst: 20

# MCP Server connections
upstreams:
  - name: "docs-server"
    type: "unix"
    socket: "/tmp/docs.sock"
    timeout: "30s"
    allow_tools: ["search_docs", "read_file", "list_directory"]
  - name: "analytics-server"
    type: "unix"
    socket: "/tmp/analytics.sock"
    timeout: "30s"
    allow_tools: ["query_metrics", "generate_report", "export_data", "get_dashboard_data"]

# Comprehensive audit logging with hash chaining
audit:
  backend: "sqlite"
  database: "/tmp/airlock-demo-audit.db"
  retention: "7d"
  export_format: "jsonl"
  hash_chain: true  # Tamper-evident logging
  include_request_body: true
  include_response_body: true

# Full observability for demo
observability:
  metrics:
    enabled: true
    path: "/metrics"
  tracing:
    enabled: false  # Keep simple for demo
  logging:
    level: "info"
    format: "json"